### ISSUE TITLE
db migrate would fail when downgrate from version with version_1_0_4 function to no

### ISSUE THREAD

**Issue by cel-gl** [sonic-net/sonic-utilities#1183]
downgrade sonic from image db_migrator.py with version_1_0_4 to without version_1_0_4 function image 

	   
Oct 21 19:28:45.007815 cel-seastone-01 ERR db_migrator[2337]: Caught exception: DBMigrator instance has no attribute 'version_1_0_4'
Oct 21 19:28:45.008557 cel-seastone-01 INFO database.sh[1854]: Traceback (most recent call last):
Oct 21 19:28:45.009149 cel-seastone-01 INFO database.sh[1854]:   File "/usr/bin/db_migrator.py", line 352, in main
Oct 21 19:28:45.009726 cel-seastone-01 INFO database.sh[1854]:     result = getattr(dbmgtr, operation)()
Oct 21 19:28:45.010272 cel-seastone-01 INFO database.sh[1854]:   File "/usr/bin/db_migrator.py", line 307, in migrate
Oct 21 19:28:45.010836 cel-seastone-01 INFO database.sh[1854]:     next_version = getattr(self, version)()
Oct 21 19:28:45.011474 cel-seastone-01 INFO database.sh[1854]: AttributeError: DBMigrator instance has no attribute 'version_1_0_4'
Oct 21 19:28:45.016736 cel-seastone-01 INFO database.sh[1854]: DBMigrator instance has no attribute 'version_1_0_4'
Oct 21 19:28:45.017550 cel-seastone-01 INFO database.sh[1854]: usage: db_migrator.py [-h] [-o operation migrate, set_version, get_version]
Oct 21 19:28:45.018261 cel-seastone-01 INFO database.sh[1854]:                       [-s unix socket] [-n asic namespace]
Oct 21 19:28:45.019008 cel-seastone-01 INFO database.sh[1854]: optional arguments:
Oct 21 19:28:45.019715 cel-seastone-01 INFO database.sh[1854]:   -h, --help            show this help message and exit
Oct 21 19:28:45.020423 cel-seastone-01 INFO database.sh[1854]:   -o operation (migrate, set_version, get_version)

    def version_1_0_3(self):
        """
        Current latest version. Nothing to do here.
        """
        log.log_info('Handling version_1_0_3')

        self.set_version('version_1_0_4')

        return 'version_1_0_4'

    def version_1_0_4(self):
        """
        Current latest version. Nothing to do here.
        """
        log.log_info('Handling version_1_0_4')

        return None

    def get_version(self):
        version = self.configDB.get_entry(self.TABLE_NAME, self.TABLE_KEY)
        if version and version[self.TABLE_FIELD]:
            return version[self.TABLE_FIELD]

        return 'version_unknown'

    def migrate(self):
        version = self.get_version()
        log.log_info('Upgrading from version ' + version)
        while version:
            next_version = getattr(self, version)()
            if next_version == version:
                raise Exception('Version migrate from %s stuck in same version' % version)
            version = next_version

**Comment by 62010198** [comment]
there are some depencys between them, if db migrate fail , container could not start

**Comment by anshuv-mfst** [comment]
Known issue, downgrade is not supported.
