### ISSUE TITLE
'show feature autorestart' fails when there is a feature with a missing auto_resrtart attribute in CONFIG_DB

### ISSUE THREAD

**Issue by kartik-arista** [sonic-net/sonic-utilities#2587]
#### Description

The failure is as below.

```
show feature autorestart
Traceback (most recent call last):
  File "/usr/local/bin/show", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/show/feature.py", line 165, in feature_autorestart
    body.append([name, feature_table[name]['auto_restart']])
  ``` 
   

## Steps to reproduce the issue
1. Configure a feature in CONFIG_DB such that auto_restart setting is excluded.
2. Run the 'show feature autorestart' command

#### Describe the results you received

The show command should complete successfully

#### Describe the results you expected

The show coimmand failed as above.

#### Output of `show version`

```
admin@cmp235-4:~$ admin@cmp235-4:~$ show version

SONiC Software Version: SONiC.branch.202205-ars.393f0135-buildimage.origin.202205-nightly-2023.01.05.14.58
Distribution: Debian 11.6
Kernel: 5.10.0-18-2-amd64
Build commit: e55c01078
Build date: Thu Jan  5 18:50:05 UTC 2023
Built by: jenkins@jenkins-arsonic-k8s-5-w275n

Platform: x86_64-arista_7800r3ak_36dm2_lc
HwSKU: Arista-7800R3AK-36DM2-C36
ASIC: broadcom
ASIC Count: 2
Serial Number: SSN21060167
Model Number: 7800R3AK-36DM2-LC
Hardware Revision: 29.00
Uptime: 08:07:22 up  1:15,  1 user,  load average: 5.66, 5.41, 5.36
Date: Sat 07 Jan 2023 08:07:22
```

**Comment by kartik-arista** [comment]
Please note that this is related to test failures in sonic-mgmt tracked by

https://github.com/sonic-net/sonic-mgmt/issues/6825
