### ISSUE TITLE
[sonic-package-manager] package migrate error while install new image by sonic-installer

### ISSUE THREAD

**Issue by yaqiangz** [sonic-net/sonic-utilities#2956]
#### Description
Install from image with installed sonic-package to image without this package encountered migrate error in **Nokia 7215**.

#### Steps to reproduce the issue
1. Add a new sonic application container like dhcp_relay, named dhcp_server. And installed image with this container. I can find that this container has been installed successfully. And related entry in `/var/lib/sonic-package-manager/packages.json` looks fine:
  ```
  "dhcp-server": {
          "repository": "docker-dhcp-server",
          "description": "",
          "default-reference": null,
          "installed-version": "1.0.0",
          "installed": true,
          "built-in": false,
          "image-id": "sha256:786f55375a1c7dabdfadb01f16ef18d43f415d38099e75f687208aa180760603"
      }
  ```
2. Install another image without dhcp_server package by `sonic-installer install`, encountered error while migrate package via sonic-package-manager:
  ```
  Command: chroot /tmp/image-20230531.02-fs /usr/lib/docker/docker.sh start
mount: /sys/fs/cgroup/cpu: cgroup already mounted on /sys/fs/cgroup.
mount: /sys/fs/cgroup/cpuacct: cgroup already mounted on /sys/fs/cgroup.
Command: cp /var/lib/sonic-package-manager/packages.json /tmp/image-20230531.02-fs/tmp/packages.json
Command: touch /tmp/image-20230531.02-fs/tmp/docker.sock
Command: mount --bind /var/run/docker.sock /tmp/image-20230531.02-fs/tmp/docker.sock
Command: cp /tmp/image-20230531.02-fs/etc/resolv.conf /tmp/resolv.conf.backup
Command: cp /etc/resolv.conf /tmp/image-20230531.02-fs/etc/resolv.conf
Command: chroot /tmp/image-20230531.02-fs sh -c command -v sonic-package-manager
Command: chroot /tmp/image-20230531.02-fs sonic-package-manager migrate /tmp/packages.json --dockerd-socket /tmp/docker.sock -y
migrating package dhcp-relay
skipping dhcp-relay as installed version is newer
migrating package dhcp-server
installing dhcp-server from old docker library
Command: chroot /tmp/image-20230531.02-fs /usr/lib/docker/docker.sh stop
Command: mv /tmp/image-20230531.02-fs/tmp/docker_config_backup /tmp/image-20230531.02-fs/etc/default/docker
Command: cp /tmp/resolv.conf.backup /tmp/image-20230531.02-fs/etc/resolv.conf
Command: umount -f -R /tmp/image-20230531.02-fs
Command: umount -r -f /tmp/image-20230531.02-fs
Command: rm -rf /tmp/image-20230531.02-fs
Traceback (most recent call last):
  File "/usr/local/bin/sonic-installer", line 8, in <module>
    sys.exit(sonic_installer())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sonic_installer/main.py", line 604, in install
    migrate_sonic_packages(bootloader, binary_image_version)
  File "/usr/local/lib/python3.9/dist-packages/sonic_installer/main.py", line 384, in migrate_sonic_packages
    run_command_or_raise(["chroot", new_image_mount, SONIC_PACKAGE_MANAGER, "migrate",
  File "/usr/local/lib/python3.9/dist-packages/sonic_installer/common.py", line 51, in run_command_or_raise
    raise SonicRuntimeException("Failed to run command '{0}'".format(argv))
sonic_installer.exception.SonicRuntimeException: Failed to run command '['chroot', '/tmp/image-20230531.02-fs', 'sonic-package-manager', 'migrate', '/tmp/packages.json', '--dockerd-socket', '/tmp/docker.sock', '-y']'
  ```

#### Output of `show version`

```
admin@hostname:~$ show ver

SONiC Software Version: SONiC.master-14031.340370-2217cb688
SONiC OS Version: 11
Distribution: Debian 11.7
Kernel: 5.10.0-18-2-armmp
Build commit: 2217cb688
Build date: Thu Aug 17 09:56:19 UTC 2023
Built by: cloudtest@f0a49336c000000

Platform: armhf-nokia_ixs7215_52x-r0
HwSKU: Nokia-M0-7215
ASIC: marvell
ASIC Count: 1
Serial Number: NK205210084
Model Number: 3HE16794AARA01
Hardware Revision: 3
Uptime: 09:07:49 up 39 min,  1 user,  load average: 1.40, 1.45, 1.66
Date: Tue 29 Aug 2023 09:07:49

Docker images:
REPOSITORY                    TAG                             IMAGE ID       SIZE
docker-dhcp-server            latest                          786f55375a1c   528MB
docker-orchagent              latest                          454a799852c2   356MB
docker-orchagent              master-14031.340370-2217cb688   454a799852c2   356MB
docker-teamd                  latest                          b5cae951639d   346MB
docker-teamd                  master-14031.340370-2217cb688   b5cae951639d   346MB
docker-sflow                  latest                          f09cf8d657ee   347MB
docker-sflow                  master-14031.340370-2217cb688   f09cf8d657ee   347MB
docker-fpm-frr                latest                          1a365919d27a   367MB
docker-fpm-frr                master-14031.340370-2217cb688   1a365919d27a   367MB
docker-nat                    latest                          bf6dab7d7020   347MB
docker-nat                    master-14031.340370-2217cb688   bf6dab7d7020   347MB
docker-platform-monitor       latest                          408e01dfe233   598MB
docker-platform-monitor       master-14031.340370-2217cb688   408e01dfe233   598MB
docker-macsec                 latest                          0cf162154dd5   347MB
docker-dhcp-relay             latest                          9fd376b22439   335MB
docker-eventd                 latest                          c339af78f089   329MB
docker-eventd                 master-14031.340370-2217cb688   c339af78f089   329MB
docker-snmp                   latest                          09331ee13eca   365MB
docker-snmp                   master-14031.340370-2217cb688   09331ee13eca   365MB
docker-syncd-mrvl             latest                          95a0dcdc22a7   425MB
docker-syncd-mrvl             master-14031.340370-2217cb688   95a0dcdc22a7   425MB
docker-sonic-telemetry        latest                          7ceadbea9e03   571MB
docker-sonic-telemetry        master-14031.340370-2217cb688   7ceadbea9e03   571MB
docker-router-advertiser      latest                          1cc88583d31c   329MB
docker-router-advertiser      master-14031.340370-2217cb688   1cc88583d31c   329MB
docker-lldp                   latest                          052579833a40   334MB
docker-lldp                   master-14031.340370-2217cb688   052579833a40   334MB
docker-mux                    latest                          ebd691bd36e2   342MB
docker-mux                    master-14031.340370-2217cb688   ebd691bd36e2   342MB
docker-database               latest                          42ba7f057764   329MB
docker-database               master-14031.340370-2217cb688   42ba7f057764   329MB
docker-sonic-mgmt-framework   latest                          336dd1ab079d   738MB
docker-sonic-mgmt-framework   master-14031.340370-2217cb688   336dd1ab079d   738MB
```

**Comment by yaqiangz** [comment]
@stepanblyschak Could you help to take a look?

**Comment by yaqiangz** [comment]
Fixed, https://github.com/sonic-net/sonic-utilities/pull/2973
