### ISSUE TITLE
[chassis] config qos reload fail for chassis

### ISSUE THREAD

**Issue by wenyiz2021** [sonic-net/sonic-utilities#3232]
#### Description
CLI fail for chassis  sudo config qos reload --ports Ethernet80

admin@chassis-lc05:~$ sudo config qos reload --ports Ethernet80
Traceback (most recent call last):
  File "/usr/local/bin/config", line 8, in <module>
    sys.exit(config())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/config/main.py", line 2505, in reload
    _qos_update_ports(ctx, ports, dry_run, json_data)
  File "/usr/local/lib/python3.9/dist-packages/config/main.py", line 2646, in _qos_update_ports
    port, _ = key
ValueError: too many values to unpack (expected 2)

## Steps to reproduce the issue
1. run " sudo config qos reload --ports Ethernet80" on any chassis
2.
3.

#### Output of `show version`

```
(paste your output here)
```

**Comment by wenyiz2021** [comment]
above PR merged
