### ISSUE TITLE
[cli]some error log appear when exec "show interfaces neighbor expected" command

### ISSUE THREAD

**Issue by dwleng-nps** [sonic-net/sonic-utilities#781]
**Description**

[cli]some error log appear when exec "show interfaces neighbor expected" command

**Steps to reproduce the issue**
1.run ansible 'iface_mode' script with t1

**Describe the results you received**

admin@tau1t8-01:/$ show interfaces neighbor expected
Traceback (most recent call last):
File "/usr/bin/show", line 12, in <module>
sys.exit(cli())
File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in call
return self.main(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/show/main.py", line 645, in expected
for port in natsorted(neighbor_dict['DEVICE_NEIGHBOR'].keys()):
KeyError: 'DEVICE_NEIGHBOR'
admin@tau1t8-01:/$

**Describe the results you expected**

admin@tau1t8-01:~$ show interfaces neighbor expected
LocalPort    Neighbor    NeighborPort    NeighborLoopback    NeighborMgmt    NeighborType
-----------  ----------  --------------  ------------------  --------------  --------------
Ethernet28   ARISTA01T1  Ethernet1       None                10.250.0.2      LeafRouter
Ethernet29   ARISTA02T1  Ethernet1       None                10.250.0.3      LeafRouter
Ethernet30   ARISTA03T1  Ethernet1       None                10.250.0.4      LeafRouter
Ethernet31   ARISTA04T1  Ethernet1       None                10.250.0.5      LeafRouter
admin@tau1t8-01:~$

**Additional information you deem important (e.g. issue happens only occasionally)**

**Output of `show version`**

SONiC Software Version: SONiC.nephos-master-df11b2b-201911190056.0-dirty-20191120.014533
Distribution: Debian 9.11
Kernel: 4.9.0-9-2-amd64
Build commit: 9adcc586
Build date: Thu Nov 21 02:00:00 UTC 2019
Built by: build@nps65

Platform: x86_64-accton_as7116_54x-r0
HwSKU: Accton-AS7116-54X
ASIC: nephos
Serial Number: 711654X1737002
Uptime: 06:47:41 up 17:21, 1 user, load average: 0.30, 0.23, 0.23

Docker images:
REPOSITORY TAG IMAGE ID SIZE
docker-syncd-nephos-rpc latest 8e556269be0e 594MB
docker-syncd-nephos latest 8e556269be0e 594MB
docker-syncd-nephos-dbg latest 0bd2224b1b46 422MB
docker-syncd-nephos-dbg nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 0bd2224b1b46 422MB
docker-syncd-nephos nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 0bd2224b1b46 422MB
docker-platform-monitor-dbg latest 822cfb8d7712 397MB
docker-platform-monitor-dbg nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 822cfb8d7712 397MB
docker-platform-monitor latest 822cfb8d7712 397MB
docker-platform-monitor nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 822cfb8d7712 397MB
docker-fpm-frr-dbg latest e9aa287c0c67 430MB
docker-fpm-frr-dbg nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 e9aa287c0c67 430MB
docker-fpm-frr latest e9aa287c0c67 430MB
docker-fpm-frr nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 e9aa287c0c67 430MB
docker-sflow-dbg latest b83be3838a02 378MB
docker-sflow-dbg nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 b83be3838a02 378MB
docker-sflow latest b83be3838a02 378MB
docker-sflow nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 b83be3838a02 378MB
docker-teamd-dbg latest 4bbe6423bbb9 404MB
docker-teamd-dbg nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 4bbe6423bbb9 404MB
docker-teamd latest 4bbe6423bbb9 404MB
docker-teamd nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 4bbe6423bbb9 404MB
docker-lldp-sv2 latest 5a91928ef05a 376MB
docker-lldp-sv2 nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 5a91928ef05a 376MB
docker-lldp-sv2-dbg latest 5a91928ef05a 376MB
docker-lldp-sv2-dbg nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 5a91928ef05a 376MB
docker-dhcp-relay-dbg latest 9b5975ab704c 359MB
docker-dhcp-relay-dbg nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 9b5975ab704c 359MB
docker-dhcp-relay latest 9b5975ab704c 359MB
docker-dhcp-relay nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 9b5975ab704c 359MB
docker-database-dbg latest 2f4d4b2aa7e2 355MB
docker-database-dbg nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 2f4d4b2aa7e2 355MB
docker-database latest 2f4d4b2aa7e2 355MB
docker-database nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 2f4d4b2aa7e2 355MB
docker-snmp-sv2-dbg latest 72a18efc13a3 406MB
docker-snmp-sv2-dbg nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 72a18efc13a3 406MB
docker-snmp-sv2 latest 72a18efc13a3 406MB
docker-snmp-sv2 nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 72a18efc13a3 406MB
docker-orchagent-dbg latest 34992853d9a5 419MB
docker-orchagent-dbg nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 34992853d9a5 419MB
docker-orchagent latest 34992853d9a5 419MB
docker-orchagent nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 34992853d9a5 419MB
docker-sonic-telemetry-dbg latest 932acb156980 377MB
docker-sonic-telemetry-dbg nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 932acb156980 377MB
docker-sonic-telemetry latest 932acb156980 377MB
docker-sonic-telemetry nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 932acb156980 377MB
docker-router-advertiser-dbg latest 7b9253e28770 354MB
docker-router-advertiser-dbg nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 7b9253e28770 354MB
docker-router-advertiser latest 7b9253e28770 354MB
docker-router-advertiser nephos-master-df11b2b-201911190056.0-dirty-20191120.014533 7b9253e28770 354MB

**Comment by dwleng-nps** [comment]
https://github.com/Azure/sonic-buildimage/pull/2535
